name: "Draft a release"
on:
  pull_request_target:
    types:
      - closed

jobs:
  draft_release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: "Get previous tag"
      id: previous_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
    - name: "Generate draft"
      run:
        | ./bin/update_release_draft {{ github.token }} {{ steps.previous_tag.outputs.tag }} {{ github.ref_name }} {{ github.event.number }}
