name: "Triage for Changelog"

on: pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Uploads repository content to the runner
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
          dot: true
  ensure:
    uses: "./.github/workflows/ensure_changelog_label.yml"
    needs: "triage"
